修正6

diff --git a/.github/workflows/prettier.yml b/.github/workflows/prettier.yml
--- a/.github/workflows/prettier.yml
+++ b/.github/workflows/prettier.yml
@@ -22,41 +22,11 @@ jobs:
 
       - name: Run Prettier
         id: prettier
-        run: npm run prettier --list-different ${{ env.FILE_PATTERN }}
+        run: npm run lint
         continue-on-error: true
 
-      - name: Run Markuplint
-        id: markuplint
-        run: npm run markuplint
-        continue-on-error: true
-
-      - name: Set result message
-        id: result_message
-        run: |
-          if [ -z "${{ steps.prettier.outputs.stdout }}" ] && [ -z "${{ steps.markuplint.outputs.stdout }}" ]; then
-            echo "::set-output name=result_message::No issues found"
-          else
-            echo "::set-output name=result_message::Error(s) found"
-          fi
-
-      - name: Get error log
-        id: error_log
-        run: |
-          echo "${{ steps.prettier.outputs.stdout }}"
-          echo "${{ steps.markuplint.outputs.stdout }}"
-
-      - name: Comment on pull request
-        uses: actions/github-script@v5
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
         with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const resultMessage = '${{ steps.result_message.outputs.result_message }}';
-            const errorLog = '${{ steps.error_log.outputs.stdout }}';
-            const octokit = JSON.parse('${{ toJSON(github) }}');
-
-            octokit.rest.issues.createComment({
-              owner: octokit.context.repo.owner,
-              repo: octokit.context.repo.repo,
-              issue_number: octokit.context.issue.number,
-              body: `CI result: ${resultMessage}\n\n${errorLog ? 'Error(s) found:\n\n```\n' + errorLog + '\n```' : ''}`
-            });
+          report_paths: '**/build/test-results/test/TEST-*.xml'
